Develop
jackSquirrel/mesto-server pull request #3
Opened 2020-03-03 15:00 UTC by jackSquirrel

Подключил базу данных, создал схемы карточек и пользователей, api взаимодействует в базой данных

2020-03-04 05:56 UTC, zlocate commented on controllers/card.js
> +    .catch(() => res.status(500).send({ message: 'Что-то пошло не так' }));
**Можно лучше**: Тексты ошибки на практике часто выносят во внешний JSON-словарь. Это позволяет избежать дублирования и, при необходимость легко их изменять (например с целью локализации).
В ближайшее время вы познакомитесь с паттерном централизованной обработки ошибок при помощи middleware.

2020-03-04 05:58 UTC, zlocate commented on models/card.js
> +        return /https?:\/\/\S+(?:jpg|jpeg|png)/.test(link);
Нужно исправить: Данное регулярное выражение пропускает некорректные ссылки, например `http://ya.ru1.jpg`

2020-03-04 06:02 UTC, zlocate commented on models/card.js
> +  createdAt: {
**Информация**: Ваш подход корректен, однако для расширения кругозора обращая внимание, что в Mongoose есть стандартный способ указания на необходимость создания полей, отражающих время последнего создания и изменения документа
https://mongoosejs.com/docs/guide.html#timestamps

2020-03-04 06:03 UTC, zlocate commented on models/card.js
> +{ versionKey: false });
**Информация**: На всякий случай расскажу зачем на практике используется данное поле.
```
The versionKey is a property set on each document when first created by Mongoose. This keys value contains the internal revision of the document. The name of this document property is configurable. The default is __v.

If this conflicts with your application you can configure as such
```
Это нужно например при реализации паттерна Optimistic Concurrency Control (https://en.wikipedia.org/wiki/Optimistic_concurrency_control)
Представим ситуацию, что в высоконагруженной системе прилетает множество запросов изменяющих параллельно один и тот же документ. (хотя лучше проектировать систему так, чтобы таких кейсов было по минимуму, смотрим в сторону Message Queue и других решений) Т.е вы считали документ, рассчитываете изменения, а в это же время другим запросом он был изменен, соответственно вы ориентируетесь на старые данные. И для того, чтобы понимать что документ изменился используют поле версии.
Но Mongoose его обновляет далеко не для всех типов документов и приходится такие вещи реализовывать снаружи :)

2020-03-04 06:04 UTC, zlocate commented on models/card.js
> +{ versionKey: false });
В рамках учебной работы поле версии можно отключить :)

2020-03-04 06:05 UTC, zlocate commented on models/user.js
> +        return /https?:\/\/\S+(?:jpg|jpeg|png)/.test(link);
Нужно исправить: используется то же регулярное выражение, что и для карточки. К сожалению, обладает тем же недостатком

2020-03-04 06:09 UTC, zlocate commented on routes/cards.js
>  const fileName = path.join(__dirname, '../data/cards.json');
Можно лучше: данный JSON-файл не используется в рамках данной работы. Рекомендуется убрать.

2020-03-04 06:10 UTC, zlocate commented on routes/cards.js
>  const fs = require('fs');
Можно лучше: Данный модуль не используется. Рекомендуется удалить

2020-03-04 06:10 UTC, zlocate commented on routes/users.js
>  const fs = require('fs');
**Можно лучше**: Данный модуль не используется. Рекомендуется удалить

2020-03-04 06:10 UTC, zlocate commented on routes/users.js
> +const { getUsers, getUser, createUser, refreshProfile, refreshAvatar } = require('../controllers/user');
**Можно лучше**: данный JSON-файл не используется в рамках данной работы. Рекомендуется убрать.

2020-03-04 06:27 UTC, zlocate commented on controllers/user.js
> +  User.create({ name, about, avatar }, { runValidators: true })
**Нужно исправить**: Создание пользовател не работает. Обратите внимание на то, как работает `runValidators:true` c `create`

2020-03-04 06:54 UTC, zlocate requested changes
Саммери: Благодарю за проделанную работу. В целом, уровень работы очень достойный.
Проверять было приятно.
Сильные стороны - аккуратность исполнения, проработка комментариев линтера, правильная реализация валидации при обновлении данных (используется `{ runValidators: true }`)
Недостатки - не работает создание пользователя и карточки, валидация url пропускает некорректные ссылки, в проекте присутствуют неиспользумые импорты и файлы от предыдущей итерации.

Работа будет принята после исправления следующих недостатков:
1. Некорректная валидация url
2. Нерабочий метод создания пользователя и карточки

2020-03-04 06:54 UTC, zlocate commented on app.js
Можно лучше: Директория `public` не используется в рамках данной работы. Поэтому ее лучше удалить

2020-03-04 06:54 UTC, zlocate commented on controllers/card.js
> +  const { name, link, likes, createdAt } = req.body;
**Можно лучше**: Подразумевается, что поле likes не доступно для заполнения при создании, а изменяется лишь при вызове методов like\unlike. Но т.к в текущей версии описания задания об этом не говорится, то я не считаю это ошибкой

2020-03-04 06:54 UTC, zlocate commented on controllers/card.js
> +  Card.create({ name, link, owner, likes, createdAt }, { runValidators: true })
**Нужно исправить**: Создание карточки завершается ошибкой. 
```
{
    "message": "card validation failed: name: Path `name` is required., link: Path `link` is required."
}
```
даже в случае когда поля заполнены корректно

2020-03-04 06:54 UTC, zlocate commented on controllers/card.js
> +const setLike = (req, res) => {
Отлично: Метод лайка работает корректно. Спасибо за выполнение дополнительного задания!

2020-03-04 06:54 UTC, zlocate commented on controllers/card.js
> +  Card.findByIdAndUpdate(req.params.cardId, { $pull: { likes: req.user._id } }, { new: true })
Отлично: Метод удаления лайка работает корректно. Спасибо за выполнение дополнительного задания!

2020-03-04 06:54 UTC, zlocate commented on controllers/user.js
> +  const { name, about } = req.body;
Можно лучше: Невозможно обновить только одно поле из двух, например только name или только about :(

2020-03-04 06:54 UTC, zlocate commented on controllers/user.js
> +  const { avatar } = req.body;
Отлично. Метод работает корректно!

2020-03-04 06:54 UTC, zlocate commented on controllers/user.js
> +const refreshProfile = (req, res) => {
**Отлично**: Спасибо за выполнение дополнительного задания!

2020-03-05 10:33 UTC, zlocate commented on controllers/card.js
> +  Card.create({ name, link, owner, likes, createdAt })
Отлично: Надеюсь вы поняли, почему данный параметр в данном контексте не нужен. Если нет, давайте обсудим :)

2020-03-05 10:34 UTC, zlocate commented on routes/users.js
> -const fs = require('fs');
Благодарю за внимание к комментариям `можно лучше`.

2020-03-05 10:35 UTC, zlocate commented on controllers/card.js
> +const errorMessage = "Что-то пошло не так";
`err.message || errorMessage` 
На мой взгляд так получается более оптимально. Обсудим?

2020-03-05 10:36 UTC, zlocate commented on models/card.js
> +{ versionKey: false },
Обсудим: Почему в данном случае нам не нужно версионирование?

2020-03-05 10:37 UTC, zlocate commented on controllers/user.js
> +  const info = req.body;
Можно лучше: Данный подход позвояет переписать произвольные поля, в т.ч те, которые не предназначены для переопределения

2020-03-05 10:38 UTC, zlocate commented
Просьба ответить на вопросы, обозначенные под префиксом `Обсудим:`

2020-03-05 10:39 UTC, zlocate commented
В целом я готов засчитать работу, но мне искренне хотелось бы услышать ваши комментарии и дать вам фидбэк.

2020-03-05 10:42 UTC, zlocate commented
Отпиште пожалуйста ваш контакт для оперативного фидбэка. Оптимальное Telegram\Viber

2020-03-05 11:57 UTC, jackSquirrel commented on controllers/card.js
> +  Card.create({ name, link, owner, likes, createdAt })
Как я понял, перечитав доку, runValidators используется только при разновидностях функции update(). Про create ничего не сказано, но, видимо, валидация происходит в данном случае автоматически

2020-03-05 11:57 UTC, jackSquirrel commented on controllers/card.js
> +const errorMessage = "Что-то пошло не так";
В момент отправки пользователю сообщения с ошибкой? В таком случае будет приходить сообщение об ошибке валидации, если ошибка со стороны пользователя, или сообщение о сбое сервера, если пользователь не при чем. Согласен, так будет лучше. В таком случае, какой статус ошибки отправлять?

2020-03-05 11:58 UTC, jackSquirrel commented on models/card.js
> +{ versionKey: false },
Насколько я понимаю, версионирование необходимо в случае, если с одним и тем же документом будет работать большое количество человек одновременно. В нашем же случае, нет необходимости использовать версионирование, поскольку в проекте не предусматривается изменение документа несколькими людьми

2020-03-05 11:58 UTC, jackSquirrel commented on controllers/user.js
> +  const info = req.body;
`if (req.body.avatar){
    res.status(400).send({ message: errorMessage });
  }`
Добавил такой код, чтобы не пропускать поле avatar

2020-03-05 11:59 UTC, jackSquirrel commented
Для оперативного фидбэка можно писать в телеграмм @jack_squirrel

2020-03-07 09:56 UTC, zlocate commented on controllers/card.js
> +const errorMessage = "Что-то пошло не так";
Пользователь передал некорректные данные - ошибка 400.
Если в процессе обработки на сервисе произошла некорректная операция то 500 (внутренняя огибка сервиса)

2020-03-07 09:56 UTC, zlocate commented on models/card.js
> +{ versionKey: false },
Разумный выбор. Принимается.
Благодарю за взвешенное решение.

2020-03-07 10:04 UTC, zlocate commented
Приветствую. Прошу прощения за задержку с проверкой работы.
Работа засчитана. Описанные выше проблемы были решены в рамках последних правок
Благодарю за внимание к деталям и осмысленность при выборе того или иного решения (это подчас важнее, чем непосредственно правильность решения).
Желаю дальнейших успехов и интересных проектов.

2020-03-07 10:10 UTC, merged