Develop
jackSquirrel/mesto-server pull request #4
Opened 2020-03-11 17:16 UTC by jackSquirrel

В проект добавлены идентификация и авторизация пользователей по email и паролю

2020-03-11 18:26 UTC, zhukovalexey76 requested changes
Требуются некоторые доработки

#### Надо исправить

1) Кажется в `.eslintrc` что-то не правильно. `no-underscore-dangle` нужно обернуть в `rules` а `_id` в массив. Вот так будет работать.

    ```text
    {
      "extends": "airbnb-base",
      "rules": {
        "no-underscore-dangle": ["error", {"allow": ["_id"]}]
      }
    }
    ```

2) Ок, теперь  `ESLint` работает. Я запускаю его в терминале вот так: `eslint . --ext .js`. И вот что получается в итоге:

    ```text
    ✖ 116 problems (115 errors, 1 warning)
      99 errors and 0 warnings potentially fixable with the `--fix` option.
    ```

    Можно автоматически исправить большую часть проблем запустив с флагом `--fix`. Вот что будет тогда: `✖ 17 problems (16 errors, 1 warning)`. Т.е. свсем немного поправить руками.
    
    P.S.: Чтобы так не мучаться я использую [prettier](https://prettier.io/). 

3) С валидацией ссылок что-то не так. Моя аватарка не проходит `https://avatars.mds.yandex.net/get-yapic/28439/m7GW8zOcuHLpiuf6CPJuqIxlEIM-1/islands-300`. Кажется дело в том что ссылка на картинку не обязана заканчиваться на `.(?:jpg|jpeg|png)`.

    Кстати `@` в regexp это не спецсомвол и её не нужно экранировать. Точка внутри `[]` тоже не считается спецсимволом и её там не нужно экранировать.

4) `.catch(() => res.status(500).send({ message: err.message || errorMessage }));`

    Кажется что `err` ни где не определен. Такая проблема есть в нескольких местах.

5) Коды статуса. В `catch` нужно различать ошибку связанную с реальной поломкой сервера (падение БД например) и ошибку связанную с валидацией данных по правилам модели. В первой случае будет статус `500 (internal error)`, во втором `400 (bad request)`.

#### Можно лучше

1) DeprecationWarning

    ```text
    DeprecationWarning: current Server Discovery and Monitoring
   engine is deprecated, and will be removed in a future version.
   To use the new Server Discover and Monitoring engine, pass option
   { useUnifiedTopology: true } to the MongoClient constructor.
    ```

    Такой вот ворнинг в консоли (терминале). Можно подумать над тем как от него избавиться.

2) Чтобы не писать везде `req.params.cardId` можно в начале контроллера дастать всё что нужно в локальные переменные `let {cardId} = req.params;` и использовать их


Напоминаю о необходимости фиксов по замечаниям с пометкой "Надо исправить".

2020-03-11 18:26 UTC, zhukovalexey76 commented on controllers/user.js
>      .catch(() => res.status(500).send({ message: err.message || errorMessage }))
**Надо исправить:** `err` не определён. Будет ошибка при попытка обратиться к свойству `message` не существующего объекта.

2020-03-11 18:26 UTC, zhukovalexey76 commented on controllers/user.js
>      .then(user => res.send(user))
**Надо исправить:** Если пользователь не найден нужно возвращать ответ с кодом `404 (not found)`. Когда передан кривой `ID` тоже можно `404` или лучше `400 (bad request)`.

https://developer.mozilla.org/ru/docs/Web/HTTP/Status/400
https://developer.mozilla.org/ru/docs/Web/HTTP/Status/404

2020-03-11 18:26 UTC, zhukovalexey76 commented on controllers/card.js
>      .catch((err) => res.status(400).send({ message: err.message || errorMessage }));
**Надо исправить:** В `catch` нужно различать ошибку связанную с реальной поломкой сервера (падение БД например) и ошибку связанную с валидацией данных по правилам модели. В первой случае будет статус `500 (internal error)`, во втором `400 (bad request)`.

https://developer.mozilla.org/ru/docs/Web/HTTP/Status/500
https://developer.mozilla.org/ru/docs/Web/HTTP/Status/400

2020-03-16 14:58 UTC, zhukovalexey76 requested changes
Еще пара небольших правок

#### Надо исправить

1) Еще один 404 в блоке then контроллера getUser

2) Пропущен return или else в deleteCard

#### Можно лучше

1) В прошлый раз был вопрос к регуляркам. Я всем рекомендую книгу с совой на обложке (Регулярные выражения | Фридл Джеффри). Читать её нужно ровно до середины. Кажется там дальше что-то специфичное для языка perl, так что нам не подходит.

2) Сравнивать ObjectID можно так `if (card.owner.equals(req.user._id)) {`


Напоминаю о необходимости фиксов по замечаниям с пометкой "Надо исправить".

2020-03-16 14:58 UTC, zhukovalexey76 commented on controllers/card.js
> +      if (card.owner.toString() !== req.user._id) {
Еще можно так: `if (card.owner.equals(req.user._id)) { ... `

2020-03-16 14:58 UTC, zhukovalexey76 commented on controllers/card.js
> +        });
**Надо исправить:** тут нужен был `return` или код ниже завернуть в блок `else` иначе дальше всегда будет выполняться удаление карточки, сразу после отправки сообщения что на это не достаточно прав =)

2020-03-16 14:58 UTC, zhukovalexey76 commented on controllers/card.js
> +  Card.findById(req.params.cardId)
**Можно лучше:** извлекаем сначала в локальную переменную `let {cardId} = req.params;` и дальше используем ее.

2020-03-16 14:58 UTC, zhukovalexey76 commented on controllers/user.js
> +    .then((user) => res.send(user))
**Нужно исправить:** а еще 404 может быть в блоке `then`.

```
    .then((user) => {
      if (!user) {
        return next({ status: 404, message: 'not found' });
      }
      return res.send(user);
    })
```

2020-03-16 14:58 UTC, zhukovalexey76 commented on controllers/user.js
> +      message: 'Что-то пошло не так',
тут можно и рассказать что примерно пошло не так

2020-03-16 14:58 UTC, zhukovalexey76 commented on controllers/user.js
> +        'some-secret-key',
Я бы вынес это ключ в отдельный модуль. Представим ситуацию что нам нужно его поменять. Тогда придётся лазать поиском по всему проекту чтобы найти все места где мы его захардкодили. К счастью таких мест пока всего два.

2020-03-16 16:56 UTC, jackSquirrel commented on controllers/user.js
> +    .then((user) => res.send(user))
Исправил, но не совсем понятно зачем это нужно. Когда делал запрос на несуществующий id возвращалась ошибка "CastError", а она у меня обрабатывается

2020-03-17 12:46 UTC, zhukovalexey76 approved these changes
Принято!

2020-03-17 12:48 UTC, merged